# syntax=docker/dockerfile:1

FROM alpine:3.21

LABEL maintainer=galihcupu

RUN \
  apk add --no-cache --virtual=run-deps \
    libstdc++ \
    libgcc \
    icu-libs \
    libintl \
    libcap \
    aspnetcore8-runtime \
    tar

RUN \
  wget -q https://download.technitium.com/dns/DnsServerPortable.tar.gz && \
  mkdir -p /app && \
  tar -zxf DnsServerPortable.tar.gz -C /app

WORKDIR /app
EXPOSE 5380 53/udp
COPY root/ /
ENTRYPOINT ["/bin/sh start.sh"]
